const $ = (s) => document.querySelector(s);
const API = '/api';
let talents = [];
let user = JSON.parse(localStorage.getItem('lunaUser') || 'null');
let token = localStorage.getItem('lunaToken') || '';
const money = (n) => new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n||0);
const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleName = (r) => ({admin:'Admin',talent:'Nhân viên',customer:'Khách hàng'})[r] || r;
const headers = () => ({'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})});
async function request(path,options={}){const res=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||`HTTP ${res.status}`);return data;}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('on');setTimeout(()=>el.classList.remove('on'),2200)}
function openModal(id){$('#'+id).classList.add('on')} function closeModal(id){$('#'+id).classList.remove('on')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));

async function loadTalents(){try{talents=await request('/talents');$('#talentCount').textContent=`${talents.length} hồ sơ`;$('#talents').innerHTML=talents.map(t=>`<article class="talent-card"><div class="talent-photo">${t.photos?.[0]?`<img src="${esc(t.photos[0])}" alt="${esc(t.displayName)}" class="talent-photo-img" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="initials" style="display:none">${esc(t.displayName.slice(0,2).toUpperCase())}</div>`:`<div class="initials">${esc(t.displayName.slice(0,2).toUpperCase())}</div>`}${t.verified?'<span class="verified">✓ VERIFIED</span>':''}</div><div class="talent-body"><div class="topline"><h3>${esc(t.displayName)}</h3><span class="muted">${esc(t.city)}</span></div><p class="muted">${t.roles.map(esc).join(' · ')}</p><div class="rate">${money(t.ratePerShift)} / ca</div><button class="btn" onclick="book('${t._id}')">Yêu cầu booking</button></div></article>`).join('')||'<div class="empty">Chưa có talent.</div>'}catch(e){$('#talents').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
function syncAccount(){ $('#accountBtn').textContent=user?`${user.name} · ${roleName(user.role)}`:'Đăng nhập'; }
$('#accountBtn').onclick=()=>user?openDashboard():openModal('authModal'); $('#footerAccount').onclick=$('#accountBtn').onclick;
$('#loginForm').onsubmit=async(e)=>{e.preventDefault();try{const data=await request('/auth/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});user=data.user;token=data.token;localStorage.setItem('lunaUser',JSON.stringify(user));localStorage.setItem('lunaToken',token);closeModal('authModal');syncAccount();toast('Đăng nhập thành công');openDashboard()}catch(err){toast(err.message)}};
function logout(){user=null;token='';localStorage.removeItem('lunaUser');localStorage.removeItem('lunaToken');$('#dashboard').classList.remove('on');syncAccount();toast('Đã đăng xuất')}
$('#logoutBtn').onclick=logout; $('#closeDashboard').onclick=()=>$('#dashboard').classList.remove('on'); $('#dashHome').onclick=(e)=>{e.preventDefault();$('#dashboard').classList.remove('on')};
function navButton(label,active=true){return `<button class="${active?'active':''}">${label}</button>`}
async function openDashboard(){if(!user)return openModal('authModal');$('#dashboard').classList.add('on');$('#dashName').textContent=user.name;$('#dashRole').textContent=roleName(user.role);$('#dashAvatar').textContent=(user.name||'L').slice(0,1).toUpperCase();$('#dashEyebrow').textContent=`${roleName(user.role).toUpperCase()} · LUNA TALENT`;$('#dashNav').innerHTML=user.role==='admin'?navButton('Tổng quan')+navButton('Tài khoản',false)+navButton('Booking',false):user.role==='talent'?navButton('Lịch của tôi')+navButton('Hồ sơ',false):navButton('Booking của tôi')+navButton('Khám phá talent',false);$('#dashContent').innerHTML='<p class="muted">Đang tải...</p>';try{if(user.role==='admin')await adminDashboard();else if(user.role==='talent')await staffDashboard();else await customerDashboard()}catch(e){$('#dashContent').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
function metric(value,label){return `<div class="metric"><b>${value}</b><small>${label}</small></div>`}
function status(s){return `<span class="status ${esc(s)}">${esc(s)}</span>`}
function fmtDate(d){return new Date(d).toLocaleDateString('vi-VN')}
async function customerDashboard(){const bookings=await request('/bookings');$('#dashTitle').textContent='Booking của tôi';$('#dashContent').innerHTML=`<div class="metric-grid">${metric(bookings.length,'Tổng booking')}${metric(bookings.filter(b=>b.status==='pending').length,'Đang chờ')}${metric(bookings.filter(b=>b.status==='confirmed').length,'Đã xác nhận')}</div><section class="dash-section"><div class="dash-section-head"><h2>Lịch sử booking</h2><button class="mini-btn primary" onclick="closeDashAndDiscover()">+ Tạo booking</button></div>${bookingCards(bookings,false)}</section>`}
async function staffDashboard(){const [profile,bookings]=await Promise.all([request('/staff/profile'),request('/staff/bookings')]);$('#dashTitle').textContent='Lịch & hồ sơ';$('#dashContent').innerHTML=`<div class="metric-grid">${metric(bookings.length,'Booking được giao')}${metric(bookings.filter(b=>b.status==='pending').length,'Chờ xử lý')}${metric(bookings.filter(b=>b.status==='confirmed').length,'Đã xác nhận')}</div><div class="profile-panel"><section class="profile-card"><div class="eyebrow">TALENT PROFILE</div><h2>${esc(profile?.displayName||user.name)}</h2><p class="muted">${esc(profile?.city||'Chưa cập nhật')}</p><div class="info-list"><div><span>Xác minh</span><b>${profile?.verified?'Đã xác minh':'Chưa xác minh'}</b></div><div><span>Hiển thị</span><b>${profile?.published?'Công khai':'Đang ẩn'}</b></div><div><span>Vai trò</span><b>${profile?.roles?.map(esc).join(', ')||'—'}</b></div></div></section><section class="info-card"><div class="eyebrow">ACCOUNT</div><h2>${esc(user.name)}</h2><p class="muted">${esc(user.email)}</p><div class="info-list"><div><span>Quyền</span><b>${roleName(user.role)}</b></div><div><span>Trạng thái</span><b>Hoạt động</b></div></div></section></div><section class="dash-section"><div class="dash-section-head"><h2>Booking được giao</h2></div>${bookingCards(bookings,true)}</section>`}
async function adminDashboard(){const [stats,users,bookings,staff]=await Promise.all([request('/admin/stats'),request('/admin/users'),request('/admin/bookings'),request('/admin/talents')]);$('#dashTitle').textContent='Tổng quan hệ thống';$('#dashContent').innerHTML=`<div class="metric-grid">${metric(stats.customers,'Khách hàng')}${metric(stats.staff,'Nhân viên')}${metric(stats.pending,'Booking chờ duyệt')}</div><section class="dash-section"><div class="dash-section-head"><h2>Tài khoản</h2><span class="muted">${users.length} tài khoản</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Người dùng</th><th>Quyền</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${esc(u.name)}</b><br><small class="muted">${esc(u.email)}</small></td><td>${roleName(u.role)}</td><td>${status(u.isActive?'active':'locked')}</td><td>${u.role==='admin'?'—':`<button class="mini-btn" onclick="toggleUser('${u._id}',${!u.isActive})">${u.isActive?'Khóa':'Mở khóa'}</button>`}</td></tr>`).join('')}</tbody></table></div></section><section class="dash-section"><div class="dash-section-head"><div><h2>Talent</h2><span class="muted">${staff.length} hồ sơ</span></div><button class="mini-btn primary" onclick="openTalentModal()">+ Thêm Talent</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Talent</th><th>Thành phố</th><th>Xác minh</th><th>Hiển thị</th><th>Thao tác</th></tr></thead><tbody>${staff.map(t=>`<tr><td><b>${esc(t.displayName)}</b><br><small class="muted">@${esc(t.owner?.username||'nhanvien')}</small></td><td>${esc(t.city)}</td><td>${t.verified?'✓ Verified':'Chưa verified'}</td><td>${t.published?'Published':'Hidden'}</td><td><button class="mini-btn primary" onclick="openTalentPhotoModal('${t._id}')">Thay ảnh</button> <button class="mini-btn" onclick="toggleTalent('${t._id}',${!t.published})">${t.published?'Ẩn':'Hiện'}</button> <button class="mini-btn danger" onclick="deleteTalent('${t._id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div></section><section class="dash-section"><div class="dash-section-head"><h2>Booking gần đây</h2><span class="muted">${bookings.length} booking</span></div>${bookingCards(bookings,true)}</section>`}
function bookingCards(items,canManage){if(!items.length)return '<div class="empty">Chưa có booking.</div>';return `<div class="booking-cards">${items.map(b=>`<article class="booking-card"><div class="topline"><h3>${esc(b.talent?.displayName||'Talent')}</h3>${status(b.status)}</div><p><b>${fmtDate(b.eventDate)}</b> · ${esc(b.startTime)} · ${b.durationHours} giờ</p><p>${esc(b.eventType)}<br>${esc(b.venue)}</p>${canManage&&b.status==='pending'?`<div class="booking-actions"><button class="mini-btn primary" onclick="setStatus('${b._id}','confirmed')">Xác nhận</button><button class="mini-btn" onclick="setStatus('${b._id}','declined')">Từ chối</button></div>`:''}</article>`).join('')}</div>`}
function closeDashAndDiscover(){$('#dashboard').classList.remove('on');document.querySelector('#discover').scrollIntoView({behavior:'smooth'})}
async function toggleUser(id,isActive){try{await request(`/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({isActive})});toast('Đã cập nhật tài khoản');openDashboard()}catch(e){toast(e.message)}}
async function setStatus(id,s){try{await request(`/bookings/${id}/status`,{method:'PATCH',body:JSON.stringify({status:s})});toast('Đã cập nhật booking');openDashboard()}catch(e){toast(e.message)}}
function book(id){if(!user)return openModal('authModal');if(user.role!=='customer')return toast('Chỉ tài khoản khách hàng tạo booking.');$('#bookingTalent').value=id;openModal('bookingModal')}
$('#bookingForm').onsubmit=async (e)=>{e.preventDefault();try{await request('/bookings',{method:'POST',body:JSON.stringify({talent:$('#bookingTalent').value,eventType:$('#eventType').value,eventDate:$('#eventDate').value,startTime:$('#startTime').value,durationHours:Number($('#durationHours').value),venue:$('#venue').value,brief:$('#brief').value})});closeModal('bookingModal');e.target.reset();toast('Đã gửi booking');openDashboard()}catch(err){toast(err.message)}};
syncAccount();loadTalents();

function openTalentModal(){ const f=document.querySelector('#talentForm'); if(f)f.reset(); document.querySelector('#talentCity').value='TP.HCM'; document.querySelector('#talentRate').value='2500000'; document.querySelector('#talentPublished').checked=true; document.querySelector('#talentPhotoPreviewWrap').style.display='none'; openModal('talentModal'); }
async function toggleTalent(id,published){try{await request(`/admin/talents/${id}`,{method:'PATCH',body:JSON.stringify({published})});toast('Đã cập nhật talent');await loadTalents();openDashboard()}catch(e){toast(e.message)}}
async function deleteTalent(id){if(!confirm('Xóa talent này? Tài khoản nhân viên và booking liên quan cũng sẽ bị xóa.'))return;try{await request(`/admin/talents/${id}`,{method:'DELETE'});toast('Đã xóa talent');await loadTalents();openDashboard()}catch(e){toast(e.message)}}
const talentPhotoInput=document.querySelector('#talentPhoto');
talentPhotoInput?.addEventListener('change',()=>{const file=talentPhotoInput.files?.[0];const wrap=document.querySelector('#talentPhotoPreviewWrap');if(!file){wrap.style.display='none';return;}document.querySelector('#talentPhotoPreview').src=URL.createObjectURL(file);wrap.style.display='block';});
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
document.querySelector('#talentForm').onsubmit=async(e)=>{e.preventDefault();try{const file=document.querySelector('#talentPhoto').files?.[0];if(!file)throw new Error('Vui lòng chọn ảnh Talent');if(file.size>5*1024*1024)throw new Error('Ảnh tối đa 5MB');const photoData=await fileToDataURL(file);await request('/admin/talents',{method:'POST',body:JSON.stringify({name:document.querySelector('#talentName').value,username:document.querySelector('#talentUsername').value,password:document.querySelector('#talentPassword').value,email:document.querySelector('#talentEmail').value,phone:document.querySelector('#talentPhone').value,city:document.querySelector('#talentCity').value,displayName:document.querySelector('#talentDisplayName').value,ratePerShift:Number(document.querySelector('#talentRate').value),roles:document.querySelector('#talentRoles').value,skills:document.querySelector('#talentSkills').value,photoData,bio:document.querySelector('#talentBio').value,verified:document.querySelector('#talentVerified').checked,published:document.querySelector('#talentPublished').checked})});closeModal('talentModal');toast('Đã tạo talent và upload ảnh');await loadTalents();openDashboard()}catch(err){toast(err.message)}};


// Admin: replace an existing Talent photo (Cloudinary in production).
function openTalentPhotoModal(id){
  const t=talents.find(x=>x._id===id);
  document.querySelector('#editTalentPhotoId').value=id;
  document.querySelector('#editTalentPhotoName').textContent=t?`Đang thay ảnh cho: ${t.displayName}`:'Chọn ảnh mới';
  document.querySelector('#editTalentPhoto').value='';
  document.querySelector('#editTalentPhotoPreviewWrap').style.display='none';
  openModal('talentPhotoModal');
}
const editTalentPhotoInput=document.querySelector('#editTalentPhoto');
editTalentPhotoInput?.addEventListener('change',()=>{
  const file=editTalentPhotoInput.files?.[0]; const wrap=document.querySelector('#editTalentPhotoPreviewWrap');
  if(!file){wrap.style.display='none';return;}
  document.querySelector('#editTalentPhotoPreview').src=URL.createObjectURL(file); wrap.style.display='block';
});
document.querySelector('#talentPhotoForm')?.addEventListener('submit',async(e)=>{
  e.preventDefault();
  try{
    const id=document.querySelector('#editTalentPhotoId').value; const file=editTalentPhotoInput.files?.[0];
    if(!file)throw new Error('Vui lòng chọn ảnh mới');
    if(file.size>5*1024*1024)throw new Error('Ảnh tối đa 5MB');
    const photoData=await fileToDataURL(file);
    await request(`/admin/talents/${id}/photo`,{method:'PATCH',body:JSON.stringify({photoData})});
    closeModal('talentPhotoModal'); toast('Đã cập nhật ảnh Talent'); await loadTalents(); await adminDashboard();
  }catch(err){toast(err.message)}
});
